### ISSUE TITLE
Inset Attribute

### ISSUE THREAD

**Issue by fornewid** [fornewid/neumorphism#19]
**Describe the request you'd like:**
If you add padding to increase neumorphism shadow and spacing,
it does not work on 'wrap_content'.
So it is better not to use `padding` for both neumorphism shadow and `padding`,
but add a separate property.
Maybe it would be nice if `gap + padding` works as actual `padding`.
```xml
<soup.neumorphism.NeumorphButton
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:padding="8dp" />
```

**Additional context:**

**Comment by lighterletter** [comment]
If I'm understanding this correctly, I think the object's bounding box should be defined in the size and contain the full widget. A user should not need to worry about increasing the padding of a view in order to get the full neumorphic effect. Adding padding to it would be anything outside of the bounding box of the shadows. So that padding == outer bounding box of light shadow + outer bounding box of dark shadow + user input.

**Comment by fornewid** [comment]
`neumorph_inset*` attributes are added in `0.2.0` version.
In detail, paddings doesn't affect background size.
Instead, use insets to reduce background size to avoid clipping.
