### ISSUE TITLE
Flat drawables

### ISSUE THREAD

**Issue by Prashast09** [fornewid/neumorphism#3]
The flat widget is not working. The drawable is actually clipping to look like this
![Screenshot_1587276300](https://user-images.githubusercontent.com/20680005/79680835-d3676b00-8231-11ea-8803-3cb53dfbaaf2.png)

**Comment by fornewid** [comment]
Can you tell me which OS was tested on, please?
(And detail enviroment.)

**Comment by Dorokhovyegor** [comment]
you have to add android:clipChildren="false". it works for me

**Comment by sugarpac** [comment]
This bug is reproducable with Android 8.1 and before, both on a real device and on the AVD simulator. 
android:clipChildren="false" to parent viewgroup seems not helpful with this situation.

An environment with Android 9.0 or 10.0 works properly, though.

**Comment by fornewid** [comment]
@sugarpac Thanks for the detail description.
I'll check on that environment.

**Comment by fornewid** [comment]
In `0.1.8` version, this issue is fixed.
You may be wondering how it was modified.

Instead of `android:clipChildren="false"`, supports padding for NeumorphShapeDrawable.

![neumorphism](https://user-images.githubusercontent.com/3405740/82107748-06cfe380-9765-11ea-8f1a-d2dac789adcf.jpeg)

In default, `12dp` padding is set.
And the padding can be customized by you. (`android:padding="20dp"`)
However, please use more than this default value.
